### ISSUE TITLE
sample

### ISSUE THREAD

**Issue by rubiin** [overnested/graphql-connections#1]
Hey there. Is there a sample app.

**Comment by cerpinn** [comment]
I've used it on https://github.com/matnbaz/matnbaz - I think that could be useful until I add some examples/sample apps.

**Comment by cerpinn** [comment]
Here are some of the places the library is used in:

- https://github.com/matnbaz/matnbaz/blob/f8e00b0f41552df61ae60ea0d69b9561601d5fe1/apps/server/src/user/user.resolver.ts#L26
- https://github.com/matnbaz/matnbaz/blob/f8e00b0f41552df61ae60ea0d69b9561601d5fe1/apps/server/src/models/connections/post.connections.ts
